### ISSUE TITLE
Cant download box

### ISSUE THREAD

**Issue by liberatomota-itcenter** [clintberry/freeswitch-vagrant#1]
Hello,

When I run the "vagrant up" it fails when on the donwload of the box:

```
default: Downloading: https://atlas.hashicorp.com/inflection/boxes/ubuntu-1404-salt/versions/0.1.0/providers/virtualbox.box
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format
```

Is the box reachable?
when I go the the URL I get a 404

Thank you

**Comment by clintberry** [comment]
I got this same error reported on another repo of mine. It looks like that box is no longer there. I will swap it out with one to replace it.
